# Generated by Django 3.1.1 on 2020-10-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idx1001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'idx1001',
                'managed': False,
            },
        ),
    ]
