# Generated by Django 3.1.1 on 2020-10-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idx1028',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1028',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1034',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1034',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1035',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1035',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1150',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1150',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1151',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1151',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1152',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1152',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1153',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1153',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1154',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1154',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1155',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1155',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1156',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1156',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1157',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1157',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1158',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1158',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1159',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1159',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1160',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1160',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1182',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1182',
                'managed': False,
            },
        ),
    ]
