# Generated by Django 3.1.1 on 2020-10-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_optimizer', '0002_idx1028_idx1034_idx1035_idx1150_idx1151_idx1152_idx1153_idx1154_idx1155_idx1156_idx1157_idx1158_idx1'),
    ]

    operations = [
        migrations.CreateModel(
            name='idx_name',
            fields=[
                ('idx', models.CharField(db_column='idx', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('registered', models.DateField(db_column='registered')),
            ],
            options={
                'db_table': 'idx_name',
                'managed': False,
            },
        ),
    ]
