# Generated by Django 3.1.1 on 2020-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_optimizer', '0003_idx_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='idx1002',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1002',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1003',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1003',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='idx1004',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('price', models.FloatField(db_column='price')),
            ],
            options={
                'db_table': 'idx1004',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='klips_data2',
            fields=[
                ('hhid', models.FloatField(db_column='hhid', primary_key=True, serialize=False)),
                ('labor_income', models.FloatField(db_column='labor income')),
                ('i0101', models.IntegerField(db_column='0101')),
                ('i0110', models.IntegerField(db_column='0110')),
                ('i0107', models.IntegerField(db_column='0107')),
                ('i5501', models.IntegerField(db_column='5501')),
                ('jobtype', models.CharField(db_column='jobtype', max_length=10)),
                ('i0330', models.IntegerField(db_column='0330')),
                ('i0150', models.IntegerField(db_column='0150')),
                ('i1406', models.IntegerField(db_column='1406')),
                ('pickle_num', models.CharField(db_column='pickle_num', max_length=2)),
            ],
            options={
                'db_table': 'klips_data2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='kospi_return',
            fields=[
                ('SymbolName', models.IntegerField(db_column='Symbol Name', primary_key=True, serialize=False)),
                ('kospi', models.FloatField(db_column='kospi')),
            ],
            options={
                'db_table': 'kospi_return',
                'managed': False,
            },
        ),
    ]
